# Filename must me exclusively `bob.yml`

base:
  project_name: "bob" # Project name to be used in the go mod
  base_url: "github.com/charmingruby" # Base url to be used in the go mod
  root_dir: "dummy" # Root directory where the project is present
  source_dir: "internal" # Source directory where the source code is present
  library_dir: "pkg" # Library directory where external packages are present
